### ISSUE TITLE
Heslo pro přihlášení do aplikace?

### ISSUE THREAD

**Issue by dusekdan** [castamir/PDB-projekt#9]
Ahoj,

mám tento rok zapsané PDB a chtěl bych se podívat, jak vypadaly předchozí projekty. Když aplikaci tak nějak zkompiluju a pustím, chce to po mně pro vstup heslo a uživatelské jméno.

Dá se někde najít, nebo mi ho můete poskytnout? Díky.

**Comment by mafian89** [comment]
Cau,

myslim, ze heslo ani login dostupne nebudou. Byli nam prideleny v ramci kurzu a nasledne smazany (pokud se nepletu).

**Comment by dusekdan** [comment]
Děkuji, za odpověď,
screen(y), jak to celé pak vypadalo náhodou někde ještě nenajdeš?

Popřípadě, napadá Tě takto nějaký jednoduchý způsob, jak to zprovoznit s vlastními loginy? Ozkouším, jestli mě to přihlásí s těmi, co nám přidělili mezitím.

**Comment by mafian89** [comment]
Nejake screeny jsou v dokumentaci. No s tema loginama to nebude tak jednoduche, potreboval by jsi vlastni Oracle databazi. Pak bys jen prenastavil properties a bylo by to, IMHO.

**Comment by dusekdan** [comment]
Děkuji za odpověď ještě jednou,

pročetl jsem dokumentaci a došel k tomu, že je třeba vytvořit ve složce _\src\cz\vutbr\fit\pdb\config_ soubor config.local.properties, ve kterém ponastavuji hodnoty dle šablony v souboru config.custom.local.properties a pak se mi již povede aplikaci "tak nějak" spustit (trochu se to gribe, ale snad to nějak rozchodím).

Děkuji za pomoc.

**Comment by castamir** [comment]
Tome? Zustaly tam jeste ty easter-eggy (napr. ten gif z futuramy u nacitani) nebo ne? :D Uprimne ted doufam, ze ne :D :D
